# utils_links.py - Centralized Investing.com URLs

# Mapeo de URLs verificadas para tickers principales
VERIFIED_URLS = {
    'AAL': 'https://www.investing.com/equities/american-airlines-group',
    'ABEV': 'https://www.investing.com/equities/ambev-pn',
    'ADBE': 'https://www.investing.com/equities/adobe-inc',
    'AMD': 'https://www.investing.com/equities/advanced-micro-devices',
    'AMZN': 'https://www.investing.com/equities/amazon-com-inc',
    'AAPL': 'https://www.investing.com/equities/apple-computer-inc',
    'BABA': 'https://www.investing.com/equities/alibaba', # Corregido
    'BRK-B': 'https://www.investing.com/equities/berkshire-hathaway',
    'CAT': 'https://www.investing.com/equities/caterpillar-inc',
    'COIN': 'https://www.investing.com/equities/coinbase-global',
    'CRM': 'https://www.investing.com/equities/salesforce-inc',
    'CVX': 'https://www.investing.com/equities/chevron',
    'DIA': 'https://www.investing.com/etfs/spdr-dj-industrial-average',
    'DIS': 'https://www.investing.com/equities/disney',
    'EEM': 'https://www.investing.com/etfs/ishares-msci-emg-markets',
    'EWZ': 'https://www.investing.com/etfs/ishares-msci-brazil-cap',
    'GE': 'https://www.investing.com/equities/general-electric',
    'GGAL.BA': 'https://www.investing.com/equities/grupo-fin-galicia-adr',
    'GLD': 'https://www.investing.com/etfs/spdr-gold-trust',
    'GLOB': 'https://www.investing.com/equities/globant-sa',
    'GOOGL': 'https://www.investing.com/equities/alphabet-inc-class-a',
    'GS': 'https://www.investing.com/equities/goldman-sachs-group',
    'IBM': 'https://www.investing.com/equities/ibm',
    'INTC': 'https://www.investing.com/equities/intel-corp',
    'IWM': 'https://www.investing.com/etfs/ishares-russell-2000',
    'JNJ': 'https://www.investing.com/equities/johnson-johnson',
    'JPM': 'https://www.investing.com/equities/jp-morgan-chase',
    'KO': 'https://www.investing.com/equities/coca-cola-co',
    'LLY': 'https://www.investing.com/equities/eli-lilly-and-company',
    'LMT': 'https://www.investing.com/equities/lockheed-martin-corp',
    'MCD': 'https://www.investing.com/equities/mcdonalds',
    'MELI': 'https://www.investing.com/equities/mercadolibre',
    'META': 'https://www.investing.com/equities/meta-platforms-inc',
    'MRK': 'https://www.investing.com/equities/merck---co',
    'MSFT': 'https://www.investing.com/equities/microsoft-corporation',
    'MSTR': 'https://www.investing.com/equities/microstrategy-inc',
    'MU': 'https://www.investing.com/equities/micron-technology',
    'NFLX': 'https://www.investing.com/equities/netflix-inc',
    'NKE': 'https://www.investing.com/equities/nike',
    'NOW': 'https://www.investing.com/equities/servicenow-inc',
    'NU': 'https://www.investing.com/equities/nu-holdings-ltd',
    'NVDA': 'https://www.investing.com/equities/nvidia-corp',
    'PBR': 'https://www.investing.com/equities/petrobras-pn',
    'PFE': 'https://www.investing.com/equities/pfizer',
    'PG': 'https://www.investing.com/equities/procter-gamble',
    'PLTR': 'https://www.investing.com/equities/palantir-technologies',
    'PYPL': 'https://www.investing.com/equities/paypal-inc',
    'QCOM': 'https://www.investing.com/equities/qualcomm-inc',
    'QQQ': 'https://www.investing.com/equities/invesco-qqq-trust',
    'SBUX': 'https://www.investing.com/equities/starbucks-corp',
    'SLV': 'https://www.investing.com/etfs/ishares-silver-trust',
    'SPOT': 'https://www.investing.com/equities/spotify-technology',
    'SPY': 'https://www.investing.com/equities/spdr-s-p-500',
    'TSLA': 'https://www.investing.com/equities/tesla-inc',
    'TSM': 'https://www.investing.com/equities/taiwan-semiconductor-manufacturing',
    'UBER': 'https://www.investing.com/equities/uber-technologies-inc',
    'UNH': 'https://www.investing.com/equities/united-health-group',
    'USO': 'https://www.investing.com/equities/united-states-oil-fund',
    'V': 'https://www.investing.com/equities/visa-inc',
    'VALE': 'https://www.investing.com/equities/vale-sa-adr',
    'VIST': 'https://www.investing.com/equities/vista-oil--gas-sabu-de-cv',
    'VZ': 'https://www.investing.com/equities/verizon-communications',
    'WMT': 'https://www.investing.com/equities/wal-mart-stores',
    'XLE': 'https://www.investing.com/etfs/energy-select-sector-spd',
    'XLF': 'https://www.investing.com/etfs/financial-select-sector-spd',
    'YPF': 'https://www.investing.com/equities/ypf-sociedad-anonima-adr',
}

def get_investing_url(ticker):
    """Retorna URL verificada si existe, sino búsqueda robusta"""
    if ticker in VERIFIED_URLS:
        return VERIFIED_URLS[ticker]
    else:
        # Fallback a búsqueda para tickers desconocidos (Garantiza que no de 404)
        return f"https://www.investing.com/search/?q={ticker}"
